title: Goldberry Interiors
description: "Goldberry Interiors by Franci Hoyt"
url: https://GoldberryInteriors.com/

# Defaults set by GitHub, only need for local serving
# https://help.github.com/articles/configuring-jekyll/
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
